### PR TITLE
ServerBase: Adds fallback localhost addresses

### LINKED ISSUE #1914: Version 2.6.12 in VS 2013 ultimate won't compile scss to css
After installing latest update, sccs to css fails.  Returning to version 2.5.1 will fix issue.
Css preview pane shows 
/*

Compilation Error occurred (see error list to navigate to the error location):

*/

The error list does not contain any errors, warnings or messages.

The build pane of the output window shows.
7/17/2015 3:48:36 PM: SCSS: Compiling Site.scss
7/17/2015 3:48:36 PM: Looking for resource @ http://localhost.:34853/
7/17/2015 3:48:36 PM: Looking for resource @ http://localhost.:34853/
7/17/2015 3:48:37 PM: Looking for resource @ http://localhost.:34853/
7/17/2015 3:48:37 PM: Looking for resource @ http://localhost.:34853/
7/17/2015 3:48:37 PM: Looking for resource @ http://localhost.:34853/
7/17/2015 3:48:37 PM: Looking for resource @ http://localhost.:34853/
7/17/2015 3:48:37 PM: Unable to find resource, aborting

I do not see any new messages in any of the system logs either.  

Any suggestions would be appreciated.  I think the overall package is great, so this is frustrating.
Thanks.

### PR DESCRIPTION
**Pull request by am11**
With some minor code improvements.

Fixes #1914.

@madskristensen, @SLaks, PTAL.

### CODE REVIEW

**Comment by am11** [comment]
@madskristensen, CI build is failing due to an unrelated reason (as we know `npm install` fails intermittently on build). Can you please rerun it?

File: EditorExtensions/Shared/Compilers/ServerBase.cs [hunk 1]
```diff
@@ -92,8 +91,11 @@ private void Dispose(bool disposing)
             {
                 using (await mutex.LockAsync())
                 {
-                    if (server == null || server._process == null || server._process.HasExited)
+                    if (server == null || server._address == null || server._process == null || server._process.HasExited)
+                    {
                         server = new T();
+                        server._address = string.Format(CultureInfo.InvariantCulture, "http://localhost.:{0}/", server.BasePort);
```
Comment (martin-s) [inline EditorExtensions/Shared/Compilers/ServerBase.cs:97]: The address is still including a point (.) in it, e.g. `http://localhost.`

**Comment by martin-s** [comment]
The address is still including a point (.) in it, e.g.  http://localhost (see my comment in "files changed".

File: EditorExtensions/Shared/Compilers/ServerBase.cs (hunk 1 above)
Comment (am11) [reply EditorExtensions/Shared/Compilers/ServerBase.cs:97]: There are two fallbacks below, one of them is `localhost` without period.

Comment (martin-s) [reply EditorExtensions/Shared/Compilers/ServerBase.cs:97]: I have actually a case where the localhost with point is going into a proxy request. Beside that, I don't get why the point is there anyway. Can you elaborate?

Comment (am11) [reply EditorExtensions/Shared/Compilers/ServerBase.cs:97]: It has been a while but if I remember it correctly, previously it was blocking the folks behind corporate proxy and using Windows 7 or Server 2012, where user has IE8 installed. So adding the dot helps.

Note that this is the negotiation time, when we turn up the node.js server for WebEssentials2013. We try to reach the server with `localhost.`, attempt five times, then fallback to `localhost`, then reattempt five more times with that and finally fallback to `127.0.0.1`. If none of the above work, we abort the node.js process and log the message in Output Window logger. Otherwise, we use the successful address for the lifetime of the given VS instance.
